### ISSUE TITLE
Uncaught ReferenceError: _ is not defined

### ISSUE THREAD

**Issue by PhilippGrulich** [bit2pixel/netflix-god-mode-bookmarklet#1]
Hey,
i allays get Uncaught ReferenceError: _ is not defined when i click on the bookmark.
can it be that netflix don´t use underscore.js anymore.?

**Comment by carlj** [comment]
same here!

Tested with Mac OS X 10.9.5 and Safari 7.1.3

**Comment by carlj** [comment]
@PhilippGrulich could you please check to which url do you get redirected if you open [http://www.netflix.com](http://www.netflix.com) in your browser?

Is it [http://www.netflix.com/browse](http://www.netflix.com/browse) or [http://www.netflix.com/WiHome](http://www.netflix.com/WiHome)

If the url is [http://www.netflix.com/browse](http://www.netflix.com/browse) than just go to your account settings and disable the **Test participation**.

**Comment by PhilippGrulich** [comment]
Oh thank you very mutch now it works:))
